version: '3'
services:
  bitcoind:
    image: "arilot/docker-bitcoind:0.17.1"
    volumes:
      - "./data/bitcoind:/bitcoin/.bitcoin"
    ports:
      - "8332:8332"
      - "18332:18332"
      - "18333:18333"
  lnd0:
    image: "thesisrobot/lnd:v0.8.0-beta"
    entrypoint: ["lnd"]
    volumes:
      - "./data/lnd0:/root/.lnd"
  lnd1:
    image: "thesisrobot/lnd:v0.8.0-beta"
    entrypoint: ["lnd"]
    volumes:
      - "./data/lnd1:/root/.lnd"
  lnd2:
    image: "thesisrobot/lnd:v0.8.0-beta"
    entrypoint: ["lnd"]
    volumes:
      - "./data/lnd2:/root/.lnd"
  lnd3:
    image: "thesisrobot/lnd:v0.8.0-beta"
    entrypoint: ["lnd"]
    volumes:
      - "./data/lnd3:/root/.lnd"
  lnd4:
    image: "thesisrobot/lnd:v0.8.0-beta"
    entrypoint: ["lnd"]
    volumes:
      - "./data/lnd4:/root/.lnd"
  manager:
    build: "."
    volumes:
      - "./data/lnd0:/mnt/lnd0"
      - "./data/lnd1:/mnt/lnd1"
      - "./data/lnd2:/mnt/lnd2"
      - "./data/lnd3:/mnt/lnd3"
      - "./data/lnd4:/mnt/lnd4"
      - "./manager:/app"
