version: '3'
services:
  bitcoind:
    image: {{ bitcoind_image }}
    volumes:
      - "./data/bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf"
    ports:
      - "8332:8332"
      - "18332:18332"
      - "18333:18333"
  {% for container in containers %}
  {{ container }}:
    image: {{ lnd_image }}
    entrypoint: ["lnd"]
    volumes:
      - "./data/{{ container }}.conf:/root/.lnd/lnd.conf"
      - "{{ container }}:/root/.lnd"
  {% endfor %}
  manager:
    build: "."
    volumes:
      {% for container in containers -%}
      - "{{ container }}:/mnt/{{ container }}"
      {% endfor -%}
      - "./manager:/app"
volumes:
  {% for container in containers -%}
  {{ container }}:
  {% endfor -%}
