version: '3'
services:
  bitcoind:
    image: {{ bitcoind_image }}
    volumes:
      - "./data/bitcoind:/bitcoin/.bitcoin"
    ports:
      - "8332:8332"
      - "18332:18332"
      - "18333:18333"
  {% for container in containers %}
  {{ container }}:
    image: {{ lnd_image }}
    entrypoint: ["lnd"]
    volumes:
      - "./data/{{ container }}:/root/.lnd"
  {% endfor %}
  manager:
    build: "."
    volumes:
      {% for container in containers -%}
      - "./data/{{ container }}:/mnt/{{ container }}"
      {% endfor -%}
      - "./manager:/app"
